name: Lint Test Build

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  basic:
    name: Lint and tests
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: 'Asia/Shanghai'
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: |
          npm run copyTrigger
          npm run build
